[build]
  # Build command for static HTML
  command = "npm run build"
  
  # Publish directory is the build folder
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
